### ISSUE TITLE
Community - Create Grants discord space

### ISSUE THREAD

**Issue by bordumb** [radicle-dev/radicle-grants#18]
## Overview

Create Grants space on discord 
https://discord.gg/cS42wyG7

**Comment by abbey-titcomb** [comment]
@bordumb need any other support on this?

**Comment by bordumb** [comment]
@abbey-titcomb good here!

![image](https://user-images.githubusercontent.com/3743841/148815340-c1a0fe0e-d9ff-44d2-8bd6-bb3984844b96.png)
